export const THEORIES_REQUEST = 'THEORIES_REQUEST';
export const THEORIES_SUCCESS = 'THEORIES_SUCCESS';
export const THEORIES_FAILURE = 'THEORIES_FAILURE';

export const THEORIES_POST_SUCCESS = 'THEORIES_POST_SUCCESS';
export const THEORIES_POST_FAILURE = 'THEORIES_POST_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const FAILURE_ERROR_RESET = '';

export const LOGOUT = 'LOGOUT';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';